server:
  port: 9011

spring:
  application:
    name: techmall-account
  datasource:
    url: jdbc:mysql://192.168.30.129:3307/techmall_db?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql

  rabbitmq:
    host: 192.168.30.129   # 换成你虚拟机的真实 IP
    port: 5672            # RabbitMQ 的标准通信端口
    username: guest       # 默认用户名
    password: guest       # 默认密码
    virtual-host: /       # 默认虚拟主机

eureka:
  client:
    register-with-eureka: true 
    fetch-registry: true       
    service-url:
      defaultZone: http://localhost:8888/eureka 
  instance:
    prefer-ip-address: true    

springdoc:
  swagger-ui:
    path: /swagger-ui.html
